config/routes.rb
RansackDemo::Application.routes.draw do
  root 'users#index'

  resources :blood_types

  resources :users

  

end

app/models/blood_type.rb
class BloodType < ActiveRecord::Base
  has_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :blood_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blood_types_controller.rb
class BloodTypesController < ApplicationController
  before_action :set_blood_type, only: [:show, :edit, :update, :destroy]

  # GET /blood_types
  # GET /blood_types.json
  def index
    @blood_types = BloodType.all
  end

  # GET /blood_types/1
  # GET /blood_types/1.json
  def show
  end

  # GET /blood_types/new
  def new
    @blood_type = BloodType.new
  end

  # GET /blood_types/1/edit
  def edit
  end

  # POST /blood_types
  # POST /blood_types.json
  def create
    @blood_type = BloodType.new(blood_type_params)

    respond_to do |format|
      if @blood_type.save
        format.html { redirect_to @blood_type, notice: 'Blood type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blood_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @blood_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_types/1
  # PATCH/PUT /blood_types/1.json
  def update
    respond_to do |format|
      if @blood_type.update(blood_type_params)
        format.html { redirect_to @blood_type, notice: 'Blood type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blood_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_types/1
  # DELETE /blood_types/1.json
  def destroy
    @blood_type.destroy
    respond_to do |format|
      format.html { redirect_to blood_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_type
      @blood_type = BloodType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_type_params
      params.require(:blood_type).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @search = User.search(params[:q])
    @users = @search.result
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :tel, :blood_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blood_types_helper.rb
module BloodTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blood_types/_form.html.erb
<%= form_for(@blood_type) do |f| %>
  <% if @blood_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood_type.errors.count, "error") %> prohibited this blood_type from being saved:</h2>

      <ul>
      <% @blood_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, maxlength: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blood_types/edit.html.erb
<h1>Editing blood_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @blood_type %> |
<%= link_to 'Back', blood_types_path %>

app/views/blood_types/index.html.erb
<h1>Listing blood_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_types.each do |blood_type| %>
      <tr>
        <td><%= blood_type.name %></td>
        <td><%= link_to 'Show', blood_type %></td>
        <td><%= link_to 'Edit', edit_blood_type_path(blood_type) %></td>
        <td><%= link_to 'Destroy', blood_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood type', new_blood_type_path %>

app/views/blood_types/new.html.erb
<h1>New blood_type</h1>

<%= render 'form' %>

<%= link_to 'Back', blood_types_path %>

app/views/blood_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blood_type.name %>
</p>

<%= link_to 'Edit', edit_blood_type_path(@blood_type) %> |
<%= link_to 'Back', blood_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RansackDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, max_length: 128 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, max_length: 128 %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.telephone_field :tel, max_length: 16 %>
  </div>
  <div class="field">
    <%= f.label :blood_type %><br>
    <%= f.collection_select :blood_type_id, BloodType.all, :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= search_form_for @search do |f| %>
  <%= f.label :name_cont %>
  <%= f.text_field :name_cont %>
  <br />
  <%= f.label :email_cont %>
  <%= f.text_field :email_cont %>
  <br />

  <%= f.label :tel_cont %>
  <%= f.text_field :tel_cont %>
  <br />

  <%= f.label :blood_type_id_in %>
  <% BloodType.all.each do |blood_type| %>
    <label>
      <%= f.check_box :blood_type_id_in, {name: 'q[blood_type_id_in][]'}, blood_type.id, nil %>
      <%= blood_type.name %>
    </label>
  <% end %>
  <br />

  <%= f.submit 'Search' %>
  <%= link_to 'Cansel', users_path %>
<% end %>
<br />

<% if @users.count == 0 %>
  <pre>表示できるユーザーはいません。</pre>
<% else %>
  <table>
    <thead>
      <tr>
        <th><%= sort_link @search, :name, 'Name' %></th>
        <th><%= sort_link @search, :email, 'Email' %></th>
        <th><%= sort_link @search, :tel, 'Tel' %></th>
        <th><%= sort_link @search, :blood_type_name, 'Blood type' %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tel %></td>
          <td><%= user.blood_type.name %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<p>
  <strong>Blood type:</strong>
  <%= @user.blood_type.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>